### ISSUE TITLE
OrientDB Enterprise Workbench 2.0.3 not started.

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb-studio#313] opened 2015-07-28 16:07 UTC
Requested OrientDB Enterprise Edition. Received email from Orient: Thanks for requesting the OrientDB Enterprise Edition software. You can get your copy here:
•	OrientDB Enterprise Edition 2.0.13 for production, to install on each server
•	OrientDB Enterprise Workbench 2.0.3, to access to your OrientDB Enterprise Servers

1. Start the 2.0.13 Orient DB server.
2. After download Workbench 2.0.3 unzip it and trying to start: start-workbench.bat. Notice that nothing happens.

**Comment by xvik** [comment] 2015-07-28 16:30
I faced the same problem after downloading. But next day orient sales contact me and I was able to ask them directly. Here is the suggestion which helped me:
```
There is a problem in the .bat file, so replace 

if exist "%ORIENTDB_HOME%\bin\server.bat" goto okHome

with

if exist "%ORIENTDB_HOME%\bin\start-workbench.bat" goto okHome
```
p.s. thanks again for sales team for great support

**Comment by shlapkov** [comment] 2015-07-28 16:51
Thanks @xvik. After manual corrections in bat file. I can start but not able connect to running server. When I am adding server and click "Test". I am getting message: Connection is alive however then I getting error in UI: java.lang.IllegalArgumentException: Invalid server '161.228.100.230' 
or 
java.lang.IllegalArgumentException: Invalid server 'localhost'

**Comment by xvik** [comment] 2015-07-28 17:02
You need to add port in server url
```
Server url: localhost:2480
Login/pass: root/root
```

**Comment by shlapkov** [comment] 2015-07-28 17:14
Unfortunately I am not able to start it any more getting exceptions:
To open the Web Console open your browser to the URL: http://161.228.100.230:2491 and use 'admin' as
 user and password to log in, unless you already changed it.

Exception in thread "Timer-0" com.orientechnologies.orient.core.exception.OSerializationException: E
rror on unmarshalling JSON content '<html><body>This site is running <a href='http://www.TeamViewer.
com'>TeamViewer</a>.<br /><br />
   Free Port 80 for other applications in advanced settings.</body></html>': content must be between
 { }
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.unwrapSource(ORecordSerializerJSON.java:399)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.fromString(ORecordSerializerJSON.java:173)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerialize
rJSON.fromString(ORecordSerializerJSON.java:169)
        at com.orientechnologies.orient.core.record.ORecordAbstract.fromJSON(ORecordAbstract.java:17
1)
        at com.orientechnologies.orient.core.record.impl.ODocument.fromJSON(ODocument.java:1653)
        at com.orientechnologies.workbench.ORealtimeMetric.fetch(ORealtimeMetric.java:62)
        at com.orientechnologies.workbench.ORealtimeMetric.fetch(ORealtimeMetric.java:48)
        at com.orientechnologies.workbench.OWorkbenchRealtimeTask.run(OWorkbenchRealtimeTask.java:24
)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
Error on client connection
java.lang.ExceptionInInitializerError
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Caused by: java.lang.IllegalStateException: Timer already cancelled.
        at java.util.Timer.sched(Timer.java:397)
        at java.util.Timer.schedule(Timer.java:248)
        at com.orientechnologies.orient.core.Orient.scheduleTask(Orient.java:332)
        at com.orientechnologies.orient.server.OClientConnectionManager.<init>(OClientConnectionMana
ger.java:58)
        at com.orientechnologies.orient.server.OClientConnectionManager.<clinit>(OClientConnectionMa
nager.java:51)
        ... 1 more
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)
Error on client connection
java.lang.NoClassDefFoundError: Could not initialize class com.orientechnologies.orient.server.OClie
ntConnectionManager
        at com.orientechnologies.orient.server.network.OServerNetworkListener.run(OServerNetworkList
ener.java:207)

**Comment by xvik** [comment] 2015-07-28 18:09
Try with fresh workbench installation (to remove your configuration). The issue is obviously specific to your environment. Most likely its trying to parse error send by somethinng (teamviewer?) from port 80 (because of incorrectly configured server in ui).

**Comment by shlapkov** [comment] 2015-07-29 14:20
Internal database became corrupted because user may enter incorrect port number 80 which orient doesn't recognize new issue: http://www.prjhub.com/#/issues/4852

**Comment by lvca** [comment] 2015-07-31 13:48
The .bat has been updated, thanks for the report.

**Comment by lvca** [comment] 2015-07-31 13:49
I'm closing this issue and will follow up on http://www.prjhub.com/#/issues/4852

**Closed by lvca** 2015-07-31 13:49 UTC
Labels: bug, waiting reply

**Comment by jillray7** [comment] 2015-07-31 16:09
Luca, what versions was this fixed with? This issue was around 2.0.7 also-- long before this was reported.

**Comment by lvca** [comment] 2015-07-31 16:25
Enterprise Edition 2.0.14-SNAPSHOT.

**Comment by jillray7** [comment] 2015-08-03 05:50
@xvik thanks for your help with this issue. @shlapkov Do you confirm that this issue with the .bat file has been fixed in Enterprise Edition 2.0.14-SNAPSHOT?

**Comment by shlapkov** [comment] 2015-08-03 16:35
Hello @jillray7 How can I confirm this? Enterprise Workbench cumming with different versions numbering for Enterprise Edition 2.0.13 I received from Orient: Enterprise Workbench 2.0.3

**Comment by jillray7** [comment] 2015-08-04 11:38
@shlapkov You're right. My apologies. You wouldn't be able to test this until the Enterprise release. @lvca If you have any comment, let us know.
