### ISSUE TITLE
WARNI Reached maximum number of concurrent connections [OServerNetworkListener]

### ISSUE THREAD

**Issue by JOSHI919** [orientechnologies/orientdb-studio#398] opened 2016-08-28 08:10 UTC
Hi,

I am freequently getting below warning in my server.

 WARNI Reached maximum number of concurrent connections (max=1000, current=4365), reject incoming connection from /XX.XX.XX.XX:AAA1  [OServerNetworkListener]
 WARNI Reached maximum number of concurrent connections (max=1000, current=4365), reject incoming connection from /XX.XX.XX.XX:AAA2 [OServerNetworkListener]

Each time port value is increased

Ex: 
/XX.XX.XX.XX:60945
/XX.XX.XX.XX:60946

I am using orient db as multi tenant db, in which each tenant will have its independent database.

In code after each operation connection is closed (connection.close();).Then also server is throwing error.

Jar files used in project are 

	1. orientdb-client-2.2.3.jar
	2. orientdb-core-2.2.3.jar
	3. orientdb-graphdb-2.2.3.jar 

In orientdb-server-config.xml file, also implemented
 entry name="storage.keepOpen" value="false"

Please help me in fixing issue.Code is as follows 

public List getData(int number) {
		
		ODatabaseDocumentTx connection=null; 
		String query= "SELECT from table";	
		try{
		connection= new OrientDocumentDbConn().getDocumentDBConnection(multiTenantID);
		List<ODocument> arrList = connection.command(new OSQLSynchQuery<ODocument>(query)).execute();
		if(!arrList.isEmpty()){
		// set data	
		}}finally{
				connection.close();
			}
		
		return data;
	}

Document database connection file, its  used as pool factory for multi tenant application.

public class OrientDocumentDbConn {
	
	public OrientDocumentDbConn(){}
	
	
	public  ODatabaseDocumentTx  getDocumentDBConnection(String multiTenantID){
		OPartitionedDatabasePoolFactory poolFactory = null;
		OPartitionedDatabasePool pool = null;
		ODatabaseDocumentTx dbConn =null;
		
		try{
			poolFactory = new OPartitionedDatabasePoolFactory(1);
			pool = poolFactory.get(dbIP+multiTenantID, userName, passowrd);
			 dbConn = pool.acquire();
	return	dbConn;
		}
		catch(Exception e){
			e.printStackTrace();
			
		}}
	}

**Comment by maggiolo00** [comment] 2016-08-29 16:01
hi @JOSHI919 

do you see some strange  in the server's log?

**Comment by tglman** [comment] 2016-08-30 10:50
hi @JOSHI919,

This problem are mitigate in the last hotfix 2.2.8, and are going to be fixed in the 2.2.9, the cause of this issue is the same of : http://www.prjhub.com/#/issues/7328

**Comment by lvca** [comment] 2016-09-23 18:46
@tglman is this issue fixed with 2.2.9 and further?

**Comment by tglman** [comment] 2016-09-26 10:10
hi,

Yes this is fixed, closing this.

**Closed** 2016-09-26 10:10 UTC
Labels: bug
