### ISSUE TITLE
Infinite basic auth popups

### ISSUE THREAD

**Issue by kalenchikov** [orientechnologies/orientdb-studio#380] opened 2016-05-31 12:08 UTC
After logged into the database in several second/couple minutes Studio shows basic auth popup. After entering correct server credentials popup is showed again. It happens infinite count of times. If you refresh page in browser basic auth popup is shown only one time and disappears after entering correct server credentials.

**Comment by maggiolo00** [comment] 2016-06-15 16:05
@kalenchikov 
if you are in loop you can hit Esc and it should break it.
Can you show me your orientdb-server-config.xml?

**Comment by maggiolo00** [comment] 2016-06-20 09:21
@kalenchikov 

any updates?

**Comment by maggiolo00** [comment] 2016-09-23 10:22
@kalenchikov 

any updates?

**Comment by maggiolo00** [comment] 2016-09-29 13:21
@kalenchikov 

can you check if you have the guest user in your orientdb-server-config.xml config file?

**Comment by maggiolo00** [comment] 2016-11-25 14:25
@kalenchikov 
i'm closing this since i'm not able to reproduce it. 
If you still have problem please reopen it. 
Thanks

**Closed by maggiolo00** 2016-11-25 14:24 UTC
Labels: bug, waiting reply
